In [4]:
import numpy as np

In [7]:
class Layer:
    def __init__(self):
        self.layer = []
    def add_layer(self, new_layer):
        self.layer.append(new_layer)
    def delete_layer(self, index):
        if 0<= index < len(self.layer):
            del self.layer[index]
    def get_layer(self, index):
        if  0<=index<len(self.layer):
            return self.layer[index]
        else:
            print("Invalid index, Layer does not exist.")
            return None
    def __str__(self):
        return str(self.layer)

In [18]:
my_layer = Layer()
my_layer.add_layer([1, 2, 3])
my_layer.add_layer([4, 5, 6])
print(my_layer)
my_layer.delete_layer(1)
print(my_layer)
print(my_layer.get_layer(0))
print(my_layer.get_layer(1))

[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3]]
[1, 2, 3]
Invalid index, Layer does not exist.
None


In [20]:
array = np.array([1, 2, 3, 4, 5]) #넘파이 행렬구조 생성
print("array의 자료형 : ", type(array))

array의 자료형 :  <class 'numpy.ndarray'>


In [22]:
array1 = np.array([1, 2, 3])
print(array1)

[1 2 3]


In [24]:
array2 = np.array([[1,2,3],[4,5,6]]) #2x3행렬
print(array2)

[[1 2 3]
 [4 5 6]]


In [26]:
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#2x2x3행렬
print(array3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
array1 = np.array([1,2,3])
print('행렬의 차원 : ', array1.ndim) #차원
print('행렬의 모양 :', array1.shape) #모양은 1차원은 3,으로 나옴
print(array1)

행렬의 차원 :  1
행렬의 모양 : (3,)
[1 2 3]


In [30]:
array2 = np.array([[1,2,3],[4,5,6]])
print('행렬의 차원 :', array2.ndim)
print('행렬의 모양 :', array2.shape)
print(array2)

행렬의 차원 : 2
행렬의 모양 : (2, 3)
[[1 2 3]
 [4 5 6]]


In [32]:
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('행렬의 차원 :', array3.ndim)
print('행렬의 모양 :', array3.shape)
print(array3)

행렬의 차원 : 3
행렬의 모양 : (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [34]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print('행렬의 차원 :', array1.ndim)
print('행렬의 모양 :', array1.shape)
print('데이터 개수 :', array1.size)
print(array1)

행렬의 차원 : 1
행렬의 모양 : (12,)
데이터 개수 : 12
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
array2 = array1.reshape(2,6) # array1의 행렬을 2x6으로 바꿈
print('행렬의 차원 :', array2.ndim)
print('행렬의 모양 :', array2.shape)
print('데이터 개수 :', array2.size)
print(array2)

행렬의 차원 : 2
행렬의 모양 : (2, 6)
데이터 개수 : 12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [38]:
array3 = array1.reshape(2,2,3)
print('행렬의 차원 :', array3.ndim)
print('행렬의 모양 :', array3.shape)
print('데이터 개수 :', array3.size)
print(array3)

행렬의 차원 : 3
행렬의 모양 : (2, 2, 3)
데이터 개수 : 12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [40]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array2 = array1.reshape(2,-1) # 12/2=6이므로 (2, 6)으로 생성
print("array2 행렬의 모양 : ", array2.shape)
print(array2)

array2 행렬의 모양 :  (2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [42]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array2 = array1.reshape(-1, 4)
print("array2 행렬의 모양 : ", array2.shape)
print(array2)

array2 행렬의 모양 :  (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print('배열의 전체 요소 : ', array1)
print('배열의 전체 요소 : ', array1[:]) 
print('배열의 5번째 요소 : ', array1[4])
print("배열의 7~10번째 요소 : ", array1[6:10])

배열의 전체 요소 :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
배열의 전체 요소 :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
배열의 5번째 요소 :  5
배열의 7~10번째 요소 :  [ 7  8  9 10]


In [46]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print('처음 배열 요소 : ', array1)
array1[10] = 99
print('11번째 요소에 99 추가 후 배열 요소 :', array1)

처음 배열 요소 :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
11번째 요소에 99 추가 후 배열 요소 : [ 1  2  3  4  5  6  7  8  9 10 99 12]


In [48]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print('처음 배열 요소 : ', array1)
array1[8 : 10] = 99
print('9~10번째 요소에 99 추가 후 배열 요소 :', array1)
array1[2:5] = [13, 14, 15] 
print('3~5번째 요소에 13~15 추가 후 배열 요소 :', array1)

처음 배열 요소 :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
9~10번째 요소에 99 추가 후 배열 요소 : [ 1  2  3  4  5  6  7  8 99 99 11 12]
3~5번째 요소에 13~15 추가 후 배열 요소 : [ 1  2 13 14 15  6  7  8 99 99 11 12]


In [8]:
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,4,15,16]])
print('배열의 전체 요소 : ', array1[:], sep='\n')
print('배열의 전체 요소 : ', array1[:,:], sep='\n')
print('-----------------')

print('배열의 2번째 행 : ', array1[1], sep='\n') # 2번째 뽑음. 즉 [n]은 인덱스 값임
print('배열의 2번째 행 : ', array1[1, :], sep='\n')
print('-----------------')

print('배열의 3행~4행 : ', array1[2:4], sep='\n') # 3~4행 뽑음. 번째 수 값임.
print('배열의 3행~4행 : ', array1[2:4, :], sep='\n')
print('-----------------')

배열의 전체 요소 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13  4 15 16]]
배열의 전체 요소 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13  4 15 16]]
-----------------
배열의 2번째 행 : 
[5 6 7 8]
배열의 2번째 행 : 
[5 6 7 8]
-----------------
배열의 3행~4행 : 
[[ 9 10 11 12]
 [13  4 15 16]]
배열의 3행~4행 : 
[[ 9 10 11 12]
 [13  4 15 16]]
-----------------


In [52]:
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,4,15,16]])
print('배열의 전체 요소 : ', array1, sep='\n')
print('-----------------')

print('배열의 2번째 열 : ', array1[:, 1], sep='\n')
print('배열의 2번째 행 : ', array1[1], sep='\n')
print('-----------------')

print('배열의 3열~4열 : ', array1[:, 2:4], sep='\n')
print('배열의 3행~4행 : ', array1[2:4], sep='\n')
print('-----------------')

배열의 전체 요소 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13  4 15 16]]
-----------------
배열의 2번째 열 : 
[ 2  6 10  4]
배열의 2번째 행 : 
[5 6 7 8]
-----------------
배열의 3열~4열 : 
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
배열의 3행~4행 : 
[[ 9 10 11 12]
 [13  4 15 16]]
-----------------


In [54]:
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,4,15,16]])
array1 = np.arange(0, 32) # 범위
array2 = array1.reshape([4,2,4])
print('배열(array2)의 전체 요소 : ', array2, sep='\n')

배열(array2)의 전체 요소 : 
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]


In [56]:
print('depth가 1인 배열 : ', array2[0,:,:], sep='\n')
print('-----------------')
print('depth가 2인 배열 : ', array2[1,:,:], sep='\n')
print('-----------------')
print('depth가 3인 배열 : ', array2[2,:,:], sep='\n')
print('-----------------')
print('depth가 4인 배열 : ', array2[3,:,:], sep='\n')
print('-----------------')

depth가 1인 배열 : 
[[0 1 2 3]
 [4 5 6 7]]
-----------------
depth가 2인 배열 : 
[[ 8  9 10 11]
 [12 13 14 15]]
-----------------
depth가 3인 배열 : 
[[16 17 18 19]
 [20 21 22 23]]
-----------------
depth가 4인 배열 : 
[[24 25 26 27]
 [28 29 30 31]]
-----------------


In [58]:
print('행(row)이 1인 배열 : ', array2[:,0,:], sep='\n')
print('-----------------')
print('행(row)이 2인 배열 : ', array2[:,1,:], sep='\n')
print('-----------------')

행(row)이 1인 배열 : 
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]
 [24 25 26 27]]
-----------------
행(row)이 2인 배열 : 
[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]
 [28 29 30 31]]
-----------------


In [60]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print('array1의 전체 요소 : ', array1, sep='\n')
print('--------------------')

array2 = array1[3:7]
print('array1의 4~7번째 요소를 Slicing한 배열(array2)', array2, sep='\n')
print('--------------------')

array2[0] = array2[0]*10 # 요소에 10을 곱함.
print('<array2의 1번째 요소를 10배 곱해준 값으로 변경>')
print('1번째 요소 변경 후의 array2 : ', array2)
print('array1의 전체 요소 : ', array1, sep='\n')

array1의 전체 요소 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------------
array1의 4~7번째 요소를 Slicing한 배열(array2)
[4 5 6 7]
--------------------
<array2의 1번째 요소를 10배 곱해준 값으로 변경>
1번째 요소 변경 후의 array2 :  [40  5  6  7]
array1의 전체 요소 : 
[ 1  2  3 40  5  6  7  8  9 10 11 12]


In [62]:
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,4,15,16]])
print('배열의 전체 요소 : ', array1, sep='\n')
print('----------------------')
print('배열의 행 합산 : ', np.sum(array1, axis=0), sep='\n') # axis=0 은 세로로 다 더함 
print('----------------------')
print('배열의 열 합산 : ', np.sum(array1, axis=1), sep='\n') # axis=1 은 가로로 다 더함
print('----------------------')

배열의 전체 요소 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13  4 15 16]]
----------------------
배열의 행 합산 : 
[28 22 36 40]
----------------------
배열의 열 합산 : 
[10 26 42 48]
----------------------


In [64]:
array1 = np.arange(0, 32)
array2 = array1.reshape([4,2,4])
print('배열(array2)의 depth 합산 : ', np.sum(array2, axis=0), sep='\n') 
# 차원이 높아지면 0부터 가장 바깥 차원으로 둠 (0=깊이, 1=행, 2=열)
print('----------------------')
print('배열의 행 합산 : ', np.sum(array2, axis=1), sep='\n')
print('----------------------')
print('배열의 열 합산 : ', np.sum(array2, axis=2), sep='\n')
print('----------------------')

배열(array2)의 depth 합산 : 
[[48 52 56 60]
 [64 68 72 76]]
----------------------
배열의 행 합산 : 
[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]
----------------------
배열의 열 합산 : 
[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]
----------------------


In [91]:
array_ = np.arange(1,19) #1~9까지 숫자
arrays = array_.reshape([2,3,3]) 
print(arrays,sep='\n')
print('')
for depth in range(len(arrays)):
    arrays[depth,:,:] = arrays[depth]+(depth+1)
print(arrays,sep='\n')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]]]
